states:
  dive:
    procedure: DiveProcedure
    error: DiveProcedure
    next: idle
  idle:
    procedure: IdleProcedure
    error: idle
    next: rotate90
  rotate90:
    procedure: RotateRightAngleProcedure
    error: IdleProcedure
    next: surface
  surface:
    procedure: SurfaceProcedure
    error: surface
    next: surface
