name: ROS CI Docker Build

on:
  push:
    branches:
      - 'master'
      - 'development'
  pull_request:
    branches:
      - 'master'
      - 'development'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build ROS Project via Docker
      run: |
        cd ros/
        ./docker_make.sh
